### ISSUE TITLE
WARNING DONT FUCKING STUPID USING THIS SHELL

### ISSUE THREAD

**Issue by xcyber02** [Naughty-SEC/pkexec-shell-executor#1]
THE OWNER HAS OBFUSCATE HIS CODE, AND ADD FUCTION REPORT TO TELEGRAM API
SO IF YOU USING THIS SHELL, THE OWNER CAN ACCESS YOUR SHELL TOO

**Comment by Naughty-SEC** [comment]
XD, what an id*ot
